### ISSUE TITLE
Please reduce repo's size

### ISSUE THREAD

**Issue by Litrop** [laipuran/LuckDraw#2]
It cost **68.36 MiB** to download this repo.
Please delete binary files because it can be built from source files.

**Comment by laipuran** [comment]
I'm solving this problem.

**Comment by Litrop** [comment]
```
> git clone git@github.com:laipuran/LuckDraw.git
Cloning into 'LuckDraw'...
remote: Enumerating objects: 619, done.
remote: Counting objects: 100% (619/619), done.
remote: Compressing objects: 100% (285/285), done.
remote: Total 1050 (delta 384), reused 454 (delta 255), pack-reused 431
Receiving objects: 100% (1050/1050), 68.56 MiB | 686.00 KiB/s, done.
Resolving deltas: 100% (578/578), done.
```
It has been solved?

**Comment by laipuran** [comment]
I added Bin folder to the git ignore file but it doesn't work... 
Let's think about it.

**Comment by laipuran** [comment]
I have no ideas about it.

**Comment by laipuran** [comment]
SPF may be woek

**Comment by Litrop** [comment]
Have you searched?
https://agvszwk.github.io/2019/05/11/gitignore%E4%B8%8D%E7%94%9F%E6%95%88%E7%9A%84%E8%A7%A3%E5%86%B3%E6%96%B9%E6%A1%88/

**Comment by laipuran** [comment]
use **--depth==1** to clone the master branch
